apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: my-service
serialPipeline:
  stages:
  - targetId: staging
    profiles: [staging]
  - targetId: prod
    profiles: [prod]
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
run:
  location: projects/all-them-containers/locations/us-central1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
requireApproval: true
run:
  location: projects/all-them-containers/locations/us-central1
